### ISSUE TITLE
Sorry I figured it out - dont know how to delete. using with geographic coordinate systems

### ISSUE THREAD

**Issue by damosdemos** [ccrook/QGIS-VectorFieldRenderer-Plugin#6]
I am trying to use the plugin on a table linked to a spatial database. The database uses a geographical coordinate system- (lats and longs).
I am trying to reproduce the actual length using a polar coordinate system with my lengths field in metres.
if I use the symbol units as mm the length changes dependent on scale, while if I use the map unit the measurements circle the globe. I can use the scale but it is fiddly.
would it be possible to have the symbol units as true metre length, or to specify the symbol units as the project units?
I have just figured out that if I change the project coord system to metre based, then everything works fine.
thanks

**Comment by ccrook** [comment]
Great you've got it sorted!  I think the question you've replaced it with is not related to the plugin, but to being able to delete data.  That depends on the data provider, and is nothing to do with the coordinate system.  Most providers are editable (eg most databases, shapefiles, etc).  Some, such as CSV text file layers, are not editable.  If you need to edit them, you can either do that using some other application (eg spreadsheet, text editor), or save the layer to a different format that is editable.

Since this is (I think) no longer an issue for the plugin I'm closing it.  But let me know if I've misunderstood.
