### ISSUE TITLE
Crash when switching from custom renderer to standard one

### ISSUE THREAD

**Issue by alexbruy** [ccrook/QGIS-VectorFieldRenderer-Plugin#7]
When I switch from renderer created by plugin to one of the standard renderers QGIS crashes. See also http://hub.qgis.org/issues/13973

**Comment by ccrook** [comment]
Thanks for raising the issue.  I think this is related to other issues which have appeared over the last year or so (first notice on Windows 64 bit platforms) seem to relate to the python SIP bindings... the C++ parts of some python objects get lost.  

In this case I suspect the fix is to include a check for a null pointer on the old symbol when changing to a new in QGIS.  This won't fix the python bindings issues but it will stop QGIS crashing... I guess the null pointer dereferencing should be locatable in a debugger.

**Comment by ccrook** [comment]
I don't think this is fixable within the python plugin.
Added a warning message to the plugin widget to alert user to risk..
